name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [ 1.11.2 ]
        otp: [ 23.0 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v3
        id: mix-cache #id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Compiled Files Cache
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-compiled

      - name: Clear cache if message
        env:
          PR_DESCR: ${{ github.event.pull_request.body }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          if grep -q "\[flush\]" <<<"$COMMIT_MSG$PR_DESCR"; then
            echo "removing cache..."
            rm -rf _build
          fi

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run credo
        run: mix credo --strict

      - name: Run Tests
        run: mix test

      - name: Run dialyzer
        run: mix dialyzer
        env:
          MIX_ENV: dev
